[tool.black]
line-length = 120
target-version = ['py38']
exclude = '''
/(
  | examples
  | build
  | .venv
  | out
)/
'''

[tool.pytest.ini_options]
addopts = "-s -p no:warnings --ignore-glob='examples/*' --ignore-glob='.venv/*'"
log_cli = 1
log_cli_level = "INFO"
log_cli_format = "[pytest][%(asctime)s][%(levelname)s][%(module)s][%(funcName)s] %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
log_level = "INFO"
pythonpath = [
  "./spark_torch_distributor"
]

markers = [
  "disable_auto_execute_mock"
]